/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * One quarterly Project containing an ordered array of Lessons. This is the atomic file the app ingests: projects are milestones, lessons are the sequence nodes.
 */
export interface FutureFounderCurriculumProject {
  /**
   * Convention: {pillarcode}-{ageband}-q{n}. Pillar codes: th,co,bu,le,cw,ex,lw,cr. e.g. cw-13-14-q1
   */
  id: string;
  title: string;
  pillar_primary: 'think' | 'communicate' | 'build' | 'lead' | 'wealth' | 'explore' | 'live_well' | 'create';
  /**
   * Keep to <=3. If a project touches every pillar, it is unfocused.
   *
   * @maxItems 3
   */
  pillars_supporting?:
    | []
    | ['think' | 'communicate' | 'build' | 'lead' | 'wealth' | 'explore' | 'live_well' | 'create']
    | [
        'think' | 'communicate' | 'build' | 'lead' | 'wealth' | 'explore' | 'live_well' | 'create',
        'think' | 'communicate' | 'build' | 'lead' | 'wealth' | 'explore' | 'live_well' | 'create'
      ]
    | [
        'think' | 'communicate' | 'build' | 'lead' | 'wealth' | 'explore' | 'live_well' | 'create',
        'think' | 'communicate' | 'build' | 'lead' | 'wealth' | 'explore' | 'live_well' | 'create',
        'think' | 'communicate' | 'build' | 'lead' | 'wealth' | 'explore' | 'live_well' | 'create'
      ];
  age_band: '9-10' | '11-12' | '13-14' | '15-16';
  quarter: number;
  /**
   * Markdown. What is cognitively/emotionally/socially REAL at this age. Cite the capability, not the aspiration.
   */
  developmental_frame: string;
  /**
   * Markdown. What 'creating value' genuinely means at THIS age. A lemonade stand and a startup are different acts, not one scaled.
   */
  authentic_value_meaning: string;
  motivation_lever: {
    /**
     * The specific psychological driver. 'Make it fun' is not a lever.
     */
    lever: 'autonomy' | 'mastery' | 'peer_status' | 'real_stakes' | 'real_audience' | 'belonging';
    /**
     * Markdown. How this project's design actually pulls that lever.
     */
    mechanism: string;
  };
  /**
   * The tangible portfolio thing the child ends with (a live offer, a published piece, a working demo).
   */
  artifact: string;
  /**
   * Observable statements a PARENT could verify. No vanity metrics.
   *
   * @minItems 2
   */
  success_criteria: [string, string, ...string[]];
  prereq_project_ids?: string[];
  /**
   * @minItems 3
   */
  lessons: [Lesson, Lesson, Lesson, ...Lesson[]];
}
export interface Lesson {
  /**
   * Parent project id + -l{n}. e.g. cw-13-14-q1-l1
   */
  id: string;
  sequence: number;
  title: string;
  /**
   * Markdown. STEP 1 — learn the concept. Tight, age-honest.
   */
  concept: string;
  /**
   * Markdown. STEP 2 — a concrete real-world example the child can picture.
   */
  real_example: string;
  /**
   * Markdown. STEP 3 — apply it, advancing the project artifact directly.
   */
  apply_task: string;
  /**
   * Markdown. STEP 4 — reflect.
   */
  reflection_prompt: string;
  /**
   * Markdown. STEP 5 — get feedback and improve.
   */
  feedback_task: string;
  /**
   * Markdown. STEP 6 — teach someone else. Weighted heavily: this is where retention lives.
   */
  teach_back_task: string;
  /**
   * Markdown. The DURABLE skill: when to reach for AI in this lesson and — more important — when NOT to (struggle first, verify, think unaided). Tools named here are disposable examples.
   */
  ai_judgment_note: string;
  /**
   * What the app must supply: printables, images, templates, a worksheet.
   */
  assets_needed?: string[];
  est_minutes: number;
  /**
   * @minItems 1
   */
  success_criteria: [string, ...string[]];
  prereq_lesson_ids?: string[];
}
